/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class VideoMediaTransmitParam {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VideoMediaTransmitParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoMediaTransmitParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_VideoMediaTransmitParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VideoMediaTransmitParam() {
    this(pjsua2JNI.new_VideoMediaTransmitParam(), true);
  }

}
